@echo off
title RentaCar - Ecosistema de Microservicios
color 0A

echo ===================================================
echo   Rentacar
echo ===================================================

echo
echo [1/13] Iniciando contenedor de MySQL...
docker-compose up -d mysql-db
echo Esperando 12 segundos para asegurar que el motor de BD este listo...
timeout /t 12 /nobreak > NUL

echo.
echo [2/13] Levantando Eureka Server (Service Registry)...
start "Eureka Server" cmd /k "cd eureka-server && title Eureka Server && mvn spring-boot:run"
echo Esperando 15 segundos para que Eureka este operativo...
timeout /t 15 /nobreak > NUL

echo.
echo [3/13] Levantando API Gateway...
start "API Gateway" cmd /k "cd api-gateway && title API Gateway && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [4/13] Levantando Ms Evaluaciones...
start "Ms Evaluaciones" cmd /k "cd ms-evaluaciones && title Ms Evaluaciones && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [5/13] Levantando Ms Extras...
start "Ms Extras" cmd /k "cd ms-extras && title Ms Extras && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [6/13] Levantando Ms Mantenimiento...
start "Ms Mantenimiento" cmd /k "cd ms-mantenimiento && title Ms Mantenimiento && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [7/13] Levantando Ms Notificaciones...
start "Ms Notificaciones" cmd /k "cd ms-notificaciones && title Ms Notificaciones && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [8/13] Levantando Ms Pagos...
start "Ms Pagos" cmd /k "cd ms-pagos && title Ms Pagos && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [9/13] Levantando Ms Reservas...
start "Ms Reservas" cmd /k "cd ms-reservas && title Ms Reservas && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [10/13] Levantando Ms Seguros...
start "Ms Seguros" cmd /k "cd ms-seguros && title Ms Seguros && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [11/13] Levantando Ms Sucursales...
start "Ms Sucursales " cmd /k "cd ms-sucursales && title Ms Sucursales && mvn spring-boot:run"
echo Esperando 8 segundos...

echo.
echo [12/13] Levantando Ms Usuarios...
start "Ms Usuarios" cmd /k "cd ms-usuarios && title Ms Usuarios && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL

echo.
echo [13/13] Levantando Ms Vehiculos...
start "Ms Vehiculos" cmd /k "cd ms-vehiculos && title Ms Vehiculos && mvn spring-boot:run"
echo Esperando 8 segundos...
timeout /t 8 /nobreak > NUL